set_operation:
  description: >
    Changes operation mode and backup reserve
  fields:
    real_mode:
      description: Mode to set to the Tesla gateway.
      example: 'self_consumption, backup'
    reserve_percent:
      description: Percentage of battery reserve
      example: 70
